### ISSUE TITLE
Loading Error (ProcedureKit error 1)

### ISSUE THREAD

**Issue by jeanetienne** [NativeConnect/public#10]
# Issue: Loading Error

1. I grabbed the latest build, and setup a `.nclibrary` from scratch.
2. Some App Store Connect information loads, but not all (see screenshots)

![Screen Shot 2021-02-08 at 12 43 40](https://user-images.githubusercontent.com/1822562/107167221-703b0500-6a0c-11eb-8073-fa8d842fe326.png)

![Screen Shot 2021-02-08 at 12 54 15](https://user-images.githubusercontent.com/1822562/107167342-c8720700-6a0c-11eb-97ff-795f2e932982.png)

## System
Native Connect 1.2.11
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) - macOS Big Sur 11.2 (20D64)

**Comment by shpakovski** [comment]
Hello @jeanetienne, thanks a lot for the report! Some proprietary API endpoints in the App Store Connect have changed last year, and I decided to rebuild non-working parts of the product for an official public API for Enterprise. This may take a while however, and I don’t have an ETA. Sorry for the inconvenience 🙏
