### ISSUE TITLE
Cannot sign in with Catalina

### ISSUE THREAD

**Issue by dreampowder** [NativeConnect/public#2]
Hi there, 
I've been trying to test this wonderful app, but i cannot add Apple ID to the app. 
Steps: 

1- Enter username and password
2- 2-Step Authentication kicks in and asks for pin
3- Enter the pin

and then i got this error:
Unexpected Network Error with a status code “Optional(400 bad request)”.

**Comment by shpakovski** [comment]
@dreampowder This looks like a regression, we’re working on a new build. Please stay tuned and sorry for the inconvenience!

**Comment by shpakovski** [comment]
@dreampowder It must be fixed now, could you please try the debug build? https://install.appcenter.ms/users/vadim.shpakovski/apps/nativeconnect/distribution_groups/debug

**Comment by dreampowder** [comment]
It is working now, thanks

**Comment by shpakovski** [comment]
Thanks for confirmation!
