### ISSUE TITLE
No revenue

### ISSUE THREAD

**Issue by bixcorp** [NativeConnect/public#3]
Hi team.

I'm using NC 1.0.6 (b3b161f) and on my app dashboard, I have:
Downloads 9318 // Revenue US$ 0
IAPs 604 // Refunds US$ 86

Revenue is forever frozen to US$ 0 but IAP count has the right value.
This happens on all my apps, on multiple Apple IDs, on multiple Dev teams.

Thanks for your help.

Benoit

**Comment by shpakovski** [comment]
Hi @bixcorp, does your revenue come from In-App Purchases only? Sorry for the inconvenience.

**Comment by bixcorp** [comment]
Hi @shpakovski, most of revenue comes from iAPs but I have some paid app revenue (not for the last 90 days).

Thanks for your help and congrats for this great work.

**Comment by shpakovski** [comment]
@bixcorp Thanks for the report Benoit, it should be fixed now. Could you please check [this build](https://install.appcenter.ms/users/vadim.shpakovski/apps/nativeconnect/distribution_groups/debug)?

**Comment by bixcorp** [comment]
So cool. Works great with the latest build. Thanks!
