### ISSUE TITLE
Add support for viewing downloads in PST

### ISSUE THREAD

**Issue by benrobinson16** [NativeConnect/public#4]
I'd love to be able to view my downloads in this fabulous app in PST (in keeping with reports generated by app store connect) as well as UTC.

**Comment by shpakovski** [comment]
Hi @interestingibis, thanks for the request. To make sure, you mean a table _App Editor / General / 24h / Downloads / Hours_, correct? The first column shows a local time now, but you’d like to see UTC and PST as well. Could you please confirm?

**Comment by interestingibis** [comment]
Hi Vadim,

Yes - that is what I mean although it would be wonderful to see PST for days as well as hours! (Although I appreciate that would be a lot of work).

Thank you for this amazing app!

**Comment by shpakovski** [comment]
@interestingibis Sales and Trends in NativeConnect display the same data as in the App Store Connect. If we go with time intervals different from the website, results for days would be different. Then customers would complain about this. However, this could be implemented as an explicit Preference disabled by default, this is a nice idea, cannot agree more 👍

**Comment by shpakovski** [comment]
@interestingibis Alright, I investigated into this more. PST looks like a different mode for all charts. For instance, there is no data for ‘24 Hours’. Instead, we should change UI to ‘Yesterday’. I will consider this feature for development but cannot promise ETA. Thanks for understanding!
