### ISSUE TITLE
Cannot load apps for this account error

### ISSUE THREAD

**Issue by weac-nreese** [NativeConnect/public#5]
When I added my account it displayed a exclamation mark with this error message:

JSON payload from App Store Connect is not safe because it has got unknown keys “data/summaries/#/versionSets/#/deliverableVersion/isWatchCombo, data/summaries/#/versionSets/#/inFlightVersion/isWatchCombo, data/summaries/#/watchCombo, data/summaries/#/watchOnly”.

**Comment by shpakovski** [comment]
@weac-nreese Hey, thanks a lot for the problem report! Could you please try this build? http://install.appcenter.ms/users/vadim.shpakovski/apps/nativeconnect/distribution_groups/debug

**Comment by weac-nreese** [comment]
Using that build I get the same error with a slightly different description:

JSON payload from App Store Connect is not safe because it has got unknown keys “data/summaries/#/watchCombo, data/summaries/#/watchOnly”.

**Comment by shpakovski** [comment]
@weac-nreese Could you please share a HTTP response with a JSON payload from the Help / Debug menu? I’m vadim@nativeconnect.app

**Comment by weac-nreese** [comment]
I emailed you both a log and the API response.

**Comment by shpakovski** [comment]
I published a newer build at https://install.appcenter.ms/users/vadim.shpakovski/apps/nativeconnect/distribution_groups/debug Give it a try, thanks in advance 🙏

**Comment by weac-nreese** [comment]
Thank you for the update, it works perfectly now!
