### ISSUE TITLE
Currency issue

### ISSUE THREAD

**Issue by makoni** [NativeConnect/public#8]
Version 1.2.4 (1984D85)

The app displays Revenue value in USD but currency is displayed as local (RUB for me):

<img width="430" alt="Снимок экрана 2020-05-01 в 15 35 01" src="https://user-images.githubusercontent.com/234015/80805663-54731a80-8bc1-11ea-9d57-40523f846cb6.png">

**Comment by shpakovski** [comment]
This must be fixed in the next update, sorry for the inconvenience 😅

**Comment by shpakovski** [comment]
Done, please try 1.2.5 via Preferences / Updates / Check for Updates 🙏
